### PR TITLE
Updated Readme

### PR DESCRIPTION
**Pull request by Mnpn03**
Temporary links to unfinished Wiki, grammatical issues resolved.

### CODE REVIEW

**Comment by legolord208** [comment]
I'd say we wait until your wikis are done, and the pull request is merged :smile:

**Comment by Mnpn03** [comment]
General commands are finished.

**Comment by Mnpn03** [comment]
API completed.

**Comment by legolord208** [comment]
Since you helped me with my internet connection in our private chat, I will keep my end of the bargain

**Pull request merged**
