### PR TITLE
Improve grammar in README

### PR DESCRIPTION
**Pull request by tbodt**

### CODE REVIEW

**Comment by tbodt** [comment]
Also it would be cool to include a screenshot of that "x days until trump leaves" thing

**Comment by LEGOlord208** [comment]
"in directly in the console"
pls fix xD

**Comment by tbodt** [comment]
doing that. btw I think that nice little checkbox saying “allow edits from maintainers” is checked

~Theodore

**Comment by LEGOlord208** [comment]
Sorry, I am on mobile. :P

**Comment by tbodt** [comment]
done

**Pull request merged**
